# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PaintView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaintView
  # pod 'Firebase/Core'
  # pod 'Firebase/Database'
  # pod 'SwiftyJSON'
  # pod 'PKHUD'
end
